# Generated by Django 5.2.5 on 2025-08-27 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('infirmier', 'Infirmier'), ('kine', 'Kinésithérapeute'), ('ergo', 'Ergothérapeute'), ('psychologue', 'Psychologue'), ('medecin', 'Médecin')], default='patient', max_length=20)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('objectif_principal', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('infirmier_referent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'infirmier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehabilitation.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('emotionnel', '😊 Émotionnel'), ('physique', '💪 Physique'), ('cognitif', '🧠 Cognitif'), ('social', '👥 Social')], max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehabilitation.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('humeur_jour', models.IntegerField(blank=True, choices=[(1, '😢 Très triste'), (2, '😟 Triste'), (3, '😐 Neutre'), (4, '🙂 Content'), (5, '😊 Très content')], null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehabilitation.userprofile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireSoignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('prive', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_recus', to='rehabilitation.userprofile')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_donnes', to='rehabilitation.userprofile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.DateField()),
                ('humeur', models.IntegerField(choices=[(1, '😢 Très triste'), (2, '😟 Triste'), (3, '😐 Neutre'), (4, '🙂 Content'), (5, '😊 Très content')])),
                ('motivation', models.IntegerField(choices=[(1, '❌ Très faible'), (2, '😕 Faible'), (3, '😐 Moyenne'), (4, '😊 Bonne'), (5, '✨ Excellente')])),
                ('participation_activites', models.BooleanField(default=False)),
                ('douleur_niveau', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehabilitation.userprofile')),
            ],
            options={
                'unique_together': {('patient', 'semaine')},
            },
        ),
    ]
